### ISSUE TITLE
Java/java does not handle generic localVariableDeclaration anymore

### ISSUE THREAD

**Issue by DagSonntag** [antlr/grammars-v4#2922] opened 2022-11-16 22:48 UTC
With a recent fix to handle yield properly (by me) #2911 I noticed I accidentally broke other functionality such as a local variable declarations with generic types i.e. 
`ArrayList<Integer> myList = new ArrayList<>();`

By moving statements before LocalVariableDeclarations blockStatement this now meant that the left side of the assignments got resolved as expressions ((ArrayList < Integer) > myList). 

Hence the "fix" has to be reverted, and the best way to fix #2908 that I came up with (without breaking other functionality) was to separate identifiers from valid typeIdentifiers (see pull-request added shortly). This solves the issue and is "valid" since the yield keyword is not valid in type declarations as of Java 14. 

However, it breaks existing code using the grammar since it changes the classOrInterfaceType structure. Moreover, if it should be fully used there might be more places where it is appropriate to use the new typeIdentifier type. 

So, I am happy to take feedback and thoughts on other solutions or if you think I should do something else as well. I have added and updated examples to avoid breaking this functionality again.

**Comment by kaby76** [comment] 2022-11-17 00:07
Parsing `ArrayList<Integer> myList = new ArrayList<>();` is broken in the current grammar because it thinks `ArrayList<Integer> myList` is an expression. But, it's not because of semantics.

The problem is that expressions are not parsed correctly with relational operations. [It says in the spec](https://docs.oracle.com/javase/specs/jls/se19/html/jls-15.html#jls-15.20):

> The relational operators are syntactically left-associative (they group left-to-right).
>
> However, this fact is not useful. For example, a<b<c parses as (a<b)<c, which is always a compile-time error, because the type of a<b is always boolean and < is not an operator on boolean values.
>
> The type of a relational expression is always boolean.

It might be possible to remedy the situation with rudimentary parse tree checks of the form `a < b < c` using parser-time visitors.

**Comment by DagSonntag** [comment] 2022-11-17 09:20
> Parsing `ArrayList<Integer> myList = new ArrayList<>();` is broken in the current grammar because it thinks `ArrayList<Integer> myList` is an expression. But, it's not because of semantics.

Hi
Hmm, that is true but I don't think the left association is what causes the issue this time. It is more the order in which the rules are tested, i.e. whether to test a block statement as a LocalVariableDeclaration or as an statement expression first. If one test the latter first then the resolution gets wrong as described.

**Comment by DagSonntag** [comment] 2022-11-17 18:59
Ah, yes you are right, sorry, I misunderstood.
Is there an issue that the grammar is ambiguous though, assuming that the "right" rule is tested first? As I understand this is also how a normal Java compiler chooses between the two, or am I wrong?

Adding semantics seems like a big step only to take if nothing else works since it complicates future changes considerably :/

**Comment by kaby76** [comment] 2022-11-17 19:12
The grammar is ambiguous. Hard to say if we can refactor this to remove the ambiguity. But we already use actions in othe grammars, so adding actions here won't be anything new. I don't know what the Java compiler does but it's worth a look to see how it does this. The compiler source is open, in the jdk.

**Comment by kaby76** [comment] 2022-11-19 01:30
[Parse of blockStatement](https://github.com/openjdk/jdk/blob/906f1ca4d7c8d156d60d591d14db4b21a0180ef2/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#L2654)

The parser tries to parse a [term(TYPE | EXPR)](https://github.com/openjdk/jdk/blob/906f1ca4d7c8d156d60d591d14db4b21a0180ef2/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#L2763) in order to distinguish between a variable decl vs an expression statement. `term()` looks at type information. If it sees an identifer that is a type, the parser recognizes the [rest of the declaration](https://github.com/openjdk/jdk/blob/906f1ca4d7c8d156d60d591d14db4b21a0180ef2/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#L2772). Otherwise, it recognizes an [expression statement](https://github.com/openjdk/jdk/blob/906f1ca4d7c8d156d60d591d14db4b21a0180ef2/src/jdk.compiler/share/classes/com/sun/tools/javac/parser/JavacParser.java#L2775). Notice there is no backtracking here, so it is left-factored with the recognition of `term`.

**Comment by kaby76** [comment] 2022-11-21 16:56
Right. The compiler resolves the problem by parsing for a type or expression, i.e., `term`, which means the parser is written as though the grammar is left factored. The Antlr grammar isn't left factored, but it also doesn't do backtracking. To fix this, a semantic predicate needs to help tell which choice to take in `blockStatement`. In the semantic predicate, we could do something like the hack I implemented. But, it's pretty limited. Instead, the predicate could just parse ahead for an expression. Then, looking over the parse tree, take the appropriate choice. Otherwise, we'll need to add type information to the grammar. I just don't know how much we can get away from not including semantic information to the grammar to resolve problems like this.

**Comment by DagSonntag** [comment] 2022-11-21 17:37
Hmm, I understand that the java compiler does it in this (left factored) way, but I don't get when it would go wrong with the ambiguous ordered solution proposed. I.e. to first check for a localVariableDeclaration and then, if that does not fit, for the expression statement.
Is the outcome not the same? (for any valid java code at least)

Maybe I am slow here, but can you give an example when this solution would not work?

**Comment by kaby76** [comment] 2022-11-21 19:21
Please close this damn issue!! You changed the order of the alts for `blockStatement`, merged, and I did not know that. This was a waste of my time.

**Closed** 2022-11-21 19:57 UTC
Labels: java
