### ISSUE TITLE
antlr4: LexBasic.g4 incorrect Java source file generated (Antlr 4.5.3)

### ISSUE THREAD

**Issue by metacircle** [antlr/grammars-v4#397] opened 2016-06-02 12:26 UTC
When generating the java classes for the antlr4 grammar, in the resulting LexBasic.java file it always contains invalid code in line 18, 19:

`public static final int`
`;`

I tried to see if I could figure out the underlying issue, but I failed. Any ideas?

**Comment by teverett** [comment] 2016-06-03 14:57
I'm confused by this issue.  when I run "mvn clean package" in the antlr4 dir, I get these generated classes:

<pre>
-rw-r--r--   1 teverett  staff  157833  3 Jun 10:51 ANTLRv4Parser.java
-rw-r--r--   1 teverett  staff     935  3 Jun 10:51 ANTLRv4Parser.tokens
-rw-r--r--   1 teverett  staff   21907  3 Jun 10:51 ANTLRv4ParserBaseListener.java
-rw-r--r--   1 teverett  staff   16242  3 Jun 10:51 ANTLRv4ParserBaseVisitor.java
-rw-r--r--   1 teverett  staff   21817  3 Jun 10:51 ANTLRv4ParserListener.java
-rw-r--r--   1 teverett  staff   13015  3 Jun 10:51 ANTLRv4ParserVisitor.java
-rw-r--r--   1 teverett  staff   33747  3 Jun 10:51 ANTLRv4Lexer.java
-rw-r--r--   1 teverett  staff     935  3 Jun 10:51 ANTLRv4Lexer.tokens
</pre>
I believe the generated sources from LexBasic.g4 are in ANTLRv4Lexer.java and that file does not appears to have problems at line 18,19


<pre>
// Generated from ANTLRv4Lexer.g4 by ANTLR 4.5.3
package org.antlr.parser.antlr4;
import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.atn.*;
import org.antlr.v4.runtime.dfa.DFA;
import org.antlr.v4.runtime.misc.*;

@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class ANTLRv4Lexer extends LexerAdaptor {
	static { RuntimeMetaData.checkVersion("4.5.3", RuntimeMetaData.VERSION); }

	protected static final DFA[] _decisionToDFA;
	protected static final PredictionContextCache _sharedContextCache =
		new PredictionContextCache();
	public static final int
		TOKEN_REF=1, RULE_REF=2, LEXER_CHAR_SET=3, DOC_COMMENT=4, BLOCK_COMMENT=5, 
		LINE_COMMENT=6, INT=7, STRING_LITERAL=8, UNTERMINATED_STRING_LITERAL=9, 
		BEGIN_ARGUMENT=10, BEGIN_ACTION=11, OPTIONS=12, TOKENS=13, CHANNELS=14, 
		IMPORT=15, FRAGMENT=16, LEXER=17, PARSER=18, GRAMMAR=19, PROTECTED=20, 
		PUBLIC=21, PRIVATE=22, RETURNS=23, LOCALS=24, THROWS=25, CATCH=26, FINALLY=27, 
		MODE=28, COLON=29, COLONCOLON=30, COMMA=31, SEMI=32, LPAREN=33, RPAREN=34, 
		LBRACE=35, RBRACE=36, RARROW=37, LT=38, GT=39, ASSIGN=40, QUESTION=41, 
		STAR=42, PLUS_ASSIGN=43, PLUS=44, OR=45, DOLLAR=46, RANGE=47, DOT=48, 
		AT=49, POUND=50, NOT=51, ID=52, WS=53, ERRCHAR=54, END_ARGUMENT=55, UNTERMINATED_ARGUMENT=56, 
		ARGUMENT_CONTENT=57, END_ACTION=58, UNTERMINATED_ACTION=59, ACTION_CONTENT=60, 
		UNTERMINATED_CHAR_SET=61;

</pre>

**Comment by metacircle** [comment] 2016-06-06 05:18
I copied the needed .g4 files in my project and I have been using Gradles Antlr Plugin to generate the Java source files. This way a LexBasic.java is being generated and causing the compilation of my project to fail. Same thing gets generated when using Antlr from the Commandline to generate Java sources from the .g4 files. Maybe I am doing something wrong I am not sure.

Anyway I solved my problem by getting rid of the Antlr plugin in Gradle, and building the sources from the commandline.

**Comment by teverett** [comment] 2016-06-06 16:38
interesting.  do you have a URL to the antlr gradle plugin?


On Sun, Jun 5, 2016 at 11:18 PM, metacircle <notifications@github.com>
wrote:

> I copied the needed .g4 files in my project and I have been using Gradles
> Antlr Plugin to generate the Java source files. This way a LexBasic.java is
> being generated and causing the compilation of my project to fail. Same
> thing gets generated when using Antlr from the Commandline to generate Java
> sources from the .g4 files. Maybe I am doing something wrong I am not sure.
>
> Anyway I solved my problem by getting rid of the Antlr plugin in Gradle,
> and building the sources from the commandline.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/antlr/grammars-v4/issues/397#issuecomment-223870551>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABK1ZrfQGiPQm_m0LkF3AN6byyPBmyknks5qI62egaJpZM4IsgBA>
> .
>



-- 
A better world shall emerge based on faith and understanding  - Douglas
MacArthur

**Comment by teverett** [comment] 2016-06-09 00:52
I'm not talented with gradle, but if you look here:

https://github.com/gradle/gradle/blob/master/subprojects/antlr/antlr.gradle

You will see this:

<pre>
dependencies {
    compile project(':core')
    compile project(':plugins')

    provided "antlr:antlr:2.7.7@jar"

    compile libraries.slf4j_api
}
</pre>

Does this mean that the Gradle plugin is using Antlr 2.7.7?

**Comment by metacircle** [comment] 2016-06-13 07:18
I don't know how the plugin works internally but according to the documentation I added to my config file:

```
dependencies {
    antlr "org.antlr:antlr4:4.5" // use ANTLR version 4
}
```

The produced output was consistent with what I got using the Antlr 4.5.3 commandline tool.

**Comment by teverett** [comment] 2016-06-13 22:52
ok so I think we can safely say then that the root cause is that the Gradle plugin is using an outdated Antlr version?

**Comment by metacircle** [comment] 2016-06-14 05:08
I am not sure about that.

The root cause of my issue is that the Gradle Antlr plugin is creating a LexBasic.java file that does not compile due to invalid syntax inside it. As I said, you can create that same file with the latest stable commandline version of Antlr too. I am not sure if you are not supposed to create this file at all or if it is a bug in Antlr that causes the invalid syntax inside the .java file.

**Comment by teverett** [comment] 2016-06-15 01:54
I used this command line
<pre>
java -jar antlr-4.5.3-complete.jar  LexBasic.g4 
</pre>

which produces 

- LexBasic.java
- LexBasic.tokens

I don't see the problem at line 18,19.  Does this output match what you're getting using the same command line?

<pre>
// Generated from LexBasic.g4 by ANTLR 4.5.3
import org.antlr.v4.runtime.Lexer;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.TokenStream;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.atn.*;
import org.antlr.v4.runtime.dfa.DFA;
import org.antlr.v4.runtime.misc.*;

@SuppressWarnings({"all", "warnings", "unchecked", "unused", "cast"})
public class LexBasic extends Lexer {
        static { RuntimeMetaData.checkVersion("4.5.3", RuntimeMetaData.VERSION); }

        protected static final DFA[] _decisionToDFA;
        protected static final PredictionContextCache _sharedContextCache =
                new PredictionContextCache();
        public static final int
;
        public static String[] modeNames = {
                "DEFAULT_MODE"
        };

        public static final String[] ruleNames = {
                "Ws", "Hws", "Vws", "BlockComment", "DocComment", "LineComment", "EscSeq", 
                "EscAny", "UnicodeEsc", "DecimalNumeral", "HexDigit", "DecDigit", "BoolLiteral", 
                "CharLiteral", "SQuoteLiteral", "DQuoteLiteral", "USQuoteLiteral", "NameChar", 
                "NameStartChar", "Int", "Esc", "Colon", "DColon", "SQuote", "DQuote", 
                "LParen", "RParen", "LBrace", "RBrace", "LBrack", "RBrack", "RArrow", 
                "Lt", "Gt", "Equal", "Question", "Star", "Plus", "PlusAssign", "Underscore", 
                "Pipe", "Dollar", "Comma", "Semi", "Dot", "Range", "At", "Pound", "Tilde"
        };

        private static final String[] _LITERAL_NAMES = {
        };
        private static final String[] _SYMBOLIC_NAMES = {
        };
        public static final Vocabulary VOCABULARY = new VocabularyImpl(_LITERAL_NAMES, _SYMBOLIC_NAMES);

        /**
         * @deprecated Use {@link #VOCABULARY} instead.
         */
        @Deprecated
        public static final String[] tokenNames;
        static {
                tokenNames = new String[_SYMBOLIC_NAMES.length];
                for (int i = 0; i < tokenNames.length; i++) {
                        tokenNames[i] = VOCABULARY.getLiteralName(i);
                        if (tokenNames[i] == null) {
                                tokenNames[i] = VOCABULARY.getSymbolicName(i);
                        }

                        if (tokenNames[i] == null) {
                                tokenNames[i] = "<INVALID>";
                        }
                }
        }

</pre>

**Comment by teverett** [comment] 2016-06-15 02:02
if you look at the generated source for another grammar (I checked Pascal) it seems that you are seeing the line that should contain token definitions.  From Pascal:

<pre>
        public static final int
                AND=1, ARRAY=2, BEGIN=3, BOOLEAN=4, CASE=5, CHAR=6, CHR=7, CONST=8, DIV=9, 
                DO=10, DOWNTO=11, ELSE=12, END=13, FILE=14, FOR=15, FUNCTION=16, GOTO=17, 
                IF=18, IN=19, INTEGER=20, LABEL=21, MOD=22, NIL=23, NOT=24, OF=25, OR=26, 
                PACKED=27, PROCEDURE=28, PROGRAM=29, REAL=30, RECORD=31, REPEAT=32, SET=33, 
                THEN=34, TO=35, TYPE=36, UNTIL=37, VAR=38, WHILE=39, WITH=40, PLUS=41, 
                MINUS=42, STAR=43, SLASH=44, ASSIGN=45, COMMA=46, SEMI=47, COLON=48, EQUAL=49, 
                NOT_EQUAL=50, LT=51, LE=52, GE=53, GT=54, LPAREN=55, RPAREN=56, LBRACK=57, 
                LBRACK2=58, RBRACK=59, RBRACK2=60, POINTER=61, AT=62, DOT=63, DOTDOT=64, 
                LCURLY=65, RCURLY=66, UNIT=67, INTERFACE=68, USES=69, STRING=70, IMPLEMENTATION=71, 
                WS=72, COMMENT_1=73, COMMENT_2=74, IDENT=75, STRING_LITERAL=76, NUM_INT=77;
</pre>

LexBasic.g4 doesn't define any tokens and Antlr is outputting:

<pre>
        public static final int
;
</pre>

I think this is a bug in Antlr.

**Comment by teverett** [comment] 2016-06-15 02:35
This can be fixed on the antlr4 tree in the file `antlr4\tool\resources/org/antlr/v4/tool/templates/codegen/Java/Java.stg`, at line 891

```xml

	<if(lexer.tokens)>
	public static final int
		<lexer.tokens:{k | <k>=<lexer.tokens.(k)>}; separator=", ", wrap, anchor>;
	<endif>
```

**Comment by parrt** [comment] 2016-06-18 19:27
Ah.  this is a bug that should be moved into the antlr repo.

**Comment by teverett** [comment] 2016-06-19 15:03
Logged here

https://github.com/antlr/antlr4/issues/1214

**Closed by teverett** 2016-06-19 15:03 UTC
