### ISSUE TITLE
Cannot parse tnsnames.ora that contains "SERVICE" in host string

### ISSUE THREAD

**Issue by difu** [antlr/grammars-v4#232] opened 2015-10-30 12:01 UTC
ALIAS.FOO.BAR = (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = SOMEHOST.SERVICE.FOO.BAR) (PORT = 1521)))(CONNECT_DATA = (SERVICE_NAME = SOMESERVICE.SERVICE.FOO.BAR)))

returns

> python3 aliases.py ~/tmp/tnsnames_service.ora 
line 1:91 no viable alternative at input 'ALIAS.FOO.BAR=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=SOMEHOST.SERVICE'

Regards
Dirk

**Comment by difu** [comment] 2015-10-30 13:21
It also fails with other keywords like HOST
(HOST = SOMEHOST.**HOST**.FOO.BAR)

**Comment by NormanDunbar** [comment] 2015-11-03 22:04
Evening Difu,

I see what the problem is, SERVICE or HOST in the fully qualified (in dotted) service name r host names, are being lexed as keywords rather than IDs. This is most likely caused by the ID rule being lower in precedence than the keywords.

I'm doing some (major) work on the grammar just now, as I've discovered that Oracle allows unquoted values in an IFILE and I have probably already fixed this. I know I did something that required the ID rule being moved around in the precedence hierarchy. However, when I'm done, I'll recheck your example.

Bear with me, I started a new job today and might be delayed in icing this. Feel free to prod me from time to time if you think I'm far too tardy! Don't be shy!

Cheers,
Norm.

**Comment by NormanDunbar** [comment] 2015-11-03 22:26
Actually Dirk, looking at it, there's more to it than simple precedence. If ID is higher than SERVICE or HOST then the lexer will never see those. If lower,  then we get your problem with all keywords allowed elsewhere in the grammar.

I need new lexed rules for these names to just grab a string of text up until the next closing parenthesis. 

Something like:

SERVICE_HOST : .+? ')' ; 

Then,  in the parser rules:

host : SERVICE_HOST | IP ;

And similar or the cd_service_name rule, replacing ID (DOT ID)* with SERVICE_HOST.


But, this needs testing, I'm in bed right now! ;-)


Cheers, 
Norm.

**Comment by difu** [comment] 2015-11-04 17:08
Thanks! Looking forward!
Cheers
Dirk

**Comment by NormanDunbar** [comment] 2015-11-07 14:13
Hi Dirk,
ok, quick fix, in tnsnames.g4, find the ID lexer rule which looks like this at the moment:

`ID : [A-Za-z0-9][A-Za-z0-9_-]* ;`

and change it to this instead:

`ID : [A-Za-z0-9][A-Za-z0-9_\-\.]* ;`

Not the addition of a '\' before the last hyphen '-', which should have been there all along, but was missing, and a new addition of '\.' to allow a dot in the ID name.

Compile the grammar and it works perfectly as it is.


The longer fix, make the change as above, and change the following rules to those listed below - basically removing most of the (DOT ID)* entries in the various rules:

```
alias : ID
;

host : ID
| IP
;

cd_service_name : L_PAREN SERVICE_NAME EQUAL ID R_PAREN ;

cd_instance_name : L_PAREN INSTANCE_NAME EQUAL ID R_PAREN ;

cd_failover_mode : L_PAREN FAILOVER_MODE EQUAL fo_params R_PAREN ;

cd_global_name : L_PAREN GLOBAL_NAME EQUAL ID R_PAREN ;

cd_rdb_database : L_PAREN RDB_DATABASE EQUAL (L_SQUARE DOT ID R_SQUARE)? ID R_PAREN ;

fo_backup : L_PAREN BACKUP EQUAL ID R_PAREN ;
```

Note for cd_rdb_database, you still need the L_SQUARE DOT ID R_SQUARE stuff. Don't remove that bit.

Cheers,
Norm.

**Comment by NormanDunbar** [comment] 2015-11-07 14:58
The changes listed above have been made, and tested, in my own repository. I've raised a pull request for Terr to pull the latest tnsnames.g4 into the master branch.

Cheers,
Norm.

**Comment by parrt** [comment] 2015-11-07 16:46
Resolved by https://github.com/antlr/grammars-v4/pull/254

**Closed by parrt** 2015-11-07 16:46 UTC
