### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by oak-tree** [antlr/grammars-v4#327] opened 2016-03-17 09:01 UTC
runnning `mvn clean package install` at `grammars-v4/support` - OK!

running `mvn clean test` at `grammars-v4`  - FAILED!
# Here is the log:

`[INFO] --- antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) @ gff3 ---
Parsing :C:\Users\oak\git\study\grammars-v4\gff3\examples\NC_001633.gff
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
        at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
        at org.antlr.v4.runtime.Parser.match(Parser.java:229)
        at gff3Parser.document(gff3Parser.java:118)
        ... 29 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
        ... 31 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] khubla.com Antlr4 test mojo ........................ SUCCESS [ 11.465 s]
[INFO] ANTLR4 grammars .................................... SUCCESS [  0.004 s]
[INFO] ANTLR4 grammars support ............................ SUCCESS [  0.002 s]
[INFO] ABNF grammar ....................................... SUCCESS [ 26.560 s]
[INFO] ANTLR4 grammar ..................................... SUCCESS [  2.951 s]
[INFO] khubla.com Arithmetic grammar ...................... SUCCESS [  1.733 s]
[INFO] khubla.com 6502 ASM grammar ........................ SUCCESS [  1.803 s]
[INFO] ASN.1 grammar ...................................... SUCCESS [  3.764 s]
[INFO] ATL grammar ........................................ SUCCESS [  1.500 s]
[INFO] khubla.com BASIC grammar ........................... SUCCESS [  5.861 s]
[INFO] khubla.com BNF grammar ............................. SUCCESS [  0.572 s]
[INFO] C grammar .......................................... SUCCESS [  4.801 s]
[INFO] khubla.com Calculator grammar ...................... SUCCESS [  0.837 s]
[INFO] CLIF grammar ....................................... SUCCESS [  0.410 s]
[INFO] Clojure grammar .................................... SUCCESS [  1.436 s]
[INFO] Cobol85 grammar .................................... SUCCESS [  5.202 s]
[INFO] CPP14 grammar ...................................... SUCCESS [  3.648 s]
[INFO] khubla.com creole grammar .......................... SUCCESS [  2.001 s]
[INFO] ANTLR CSV grammar .................................. SUCCESS [  0.522 s]
[INFO] DCM grammar ........................................ SUCCESS [  0.537 s]
[INFO] ANTLR dot grammar .................................. SUCCESS [  0.403 s]
[INFO] Erlang grammar ..................................... SUCCESS [  2.346 s]
[INFO] khubla.com fasta grammar ........................... SUCCESS [  3.598 s]
[INFO] First Order Logic grammar .......................... SUCCESS [  0.304 s]
[INFO] khubla.com gff3 grammar ............................ FAILURE [  0.352 s]
[INFO] GraphQL grammar .................................... SKIPPED
[INFO] khubla.com html grammar ............................ SKIPPED
[INFO] ical grammar ....................................... SKIPPED
[INFO] IDL grammar ........................................ SKIPPED
[INFO] IRI grammar ........................................ SKIPPED
[INFO] Java grammar ....................................... SKIPPED
[INFO] Java8 grammar ...................................... SKIPPED
[INFO] ANTLR JSON grammar ................................. SKIPPED
[INFO] less grammar ....................................... SKIPPED
[INFO] khubla.com logo grammar ............................ SKIPPED
[INFO] Lua grammar ........................................ SKIPPED
[INFO] MASM grammar ....................................... SKIPPED
[INFO] memcached grammar .................................. SKIPPED
[INFO] Modelica grammar ................................... SKIPPED
[INFO] Modula2 PIM4 grammar ............................... SKIPPED
[INFO] MPS grammar ........................................ SKIPPED
[INFO] muMath grammar ..................................... SKIPPED
[INFO] khubla.com MUMPS grammar ........................... SKIPPED
[INFO] MySQL grammar ...................................... SKIPPED
[INFO] ANTLR Objective C grammar .......................... SKIPPED
[INFO] khubla.com Pascal grammar .......................... SKIPPED
[INFO] PCRE grammar ....................................... SKIPPED
[INFO] pddl logo grammar .................................. SKIPPED
[INFO] khubla.com logo grammar ............................ SKIPPED
[INFO] PeopleCode grammar ................................. SKIPPED
[INFO] Antlr pgn grammar .................................. SKIPPED
[INFO] plsql grammar ...................................... SKIPPED
[INFO] khubla.com Propositional Calculus grammar .......... SKIPPED
[INFO] Python3 grammar .................................... SKIPPED
[INFO] R grammar .......................................... SKIPPED
[INFO] RCS ................................................ SKIPPED
[INFO] khubla.com RedCode grammar ......................... SKIPPED
[INFO] Ruby-like language (Corundum) grammar .............. SKIPPED
[INFO] Scala grammar ...................................... SKIPPED
[INFO] scss grammar ....................................... SKIPPED
[INFO] ADSP 2106x SHARC assembly language ................. SKIPPED
[INFO] Smalltalk grammar .................................. SKIPPED
[INFO] ANTLR4 Sparql grammar .............................. SKIPPED
[INFO] SQLite grammar ..................................... SKIPPED
[INFO] stacktrace grammar ................................. SKIPPED
[INFO] stringtemplate grammar ............................. SKIPPED
[INFO] SUOKIF grammar ..................................... SKIPPED
[INFO] ANTLR Swift grammar ................................ SKIPPED
[INFO] khubla.com tinyc grammar ........................... SKIPPED
[INFO] tnsnames grammar ................................... SKIPPED
[INFO] khubla.com TNT grammar ............................. SKIPPED
[INFO] tsql grammar ....................................... SKIPPED
[INFO] ANTLR turtle grammar ............................... SKIPPED
[INFO] UCB logo grammar ................................... SKIPPED
[INFO] VB6 grammar ........................................ SKIPPED
[INFO] VBA grammar ........................................ SKIPPED
[INFO] verilog grammar .................................... SKIPPED
[INFO] ANTLR4 vhdl grammar ................................ SKIPPED
[INFO] Wavefront grammar .................................. SKIPPED
[INFO] webidl grammar ..................................... SKIPPED
[INFO] ANTLR XML grammar .................................. SKIPPED
[INFO] XPath grammar ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:23 min
[INFO] Finished at: 2016-03-17T10:57:34+02:00
[INFO] Final Memory: 51M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) on project gff3: Unable execute mojo: InvocationTargetException: ParseCancellationException: InputMismatchException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gff3

`

**Comment by parrt** [comment] 2016-03-23 17:32
weird. travis reports success. are you sure you have pulled latest repo? maybe it's a PC vs unix thing?

**Comment by teverett** [comment] 2016-05-01 02:17
Is this still an issue?

**Comment by teverett** [comment] 2016-06-19 00:08
@oak-tree is this still an issue?

**Comment by libliflin** [comment] 2016-07-28 23:42
I have windows; java8; 64bit and it makes it past gff3 but failes on pgn

[INFO] --- antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) @ pgn ---
Parsing :D:\grammars-v4-master\pgn\examples\.DS_Store
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammar(GrammarTestMojo.java:248)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.testGrammars(GrammarTestMojo.java:275)
        at org.antlr.mojo.antlr4test.GrammarTestMojo.execute(GrammarTestMojo.java:120)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
        at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
        at org.antlr.v4.runtime.Parser.match(Parser.java:227)
        at PGNParser.parse(PGNParser.java:128)
        ... 28 more
Caused by: org.antlr.v4.runtime.InputMismatchException
        at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
        ... 30 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] khubla.com Antlr4 test mojo ........................ SUCCESS [  4.723 s]
[INFO] ANTLR4 grammars .................................... SUCCESS [  0.000 s]
[INFO] ANTLR4 grammars support ............................ SUCCESS [  0.001 s]
[INFO] ABNF grammar ....................................... SUCCESS [  1.751 s]
[INFO] khubla.com agc grammar ............................. SUCCESS [  2.482 s]
[INFO] ANTLR4 grammar ..................................... SUCCESS [  2.135 s]
[INFO] khubla.com Arithmetic grammar ...................... SUCCESS [  1.110 s]
[INFO] khubla.com 6502 ASM grammar ........................ SUCCESS [  0.997 s]
[INFO] ASN.1 grammar ...................................... SUCCESS [  1.832 s]
[INFO] ATL grammar ........................................ SUCCESS [  0.631 s]
[INFO] khubla.com BASIC grammar ........................... SUCCESS [  2.927 s]
[INFO] khubla.com BNF grammar ............................. SUCCESS [  0.418 s]
[INFO] C grammar .......................................... SUCCESS [  2.008 s]
[INFO] khubla.com Calculator grammar ...................... SUCCESS [  0.644 s]
[INFO] CLIF grammar ....................................... SUCCESS [  0.323 s]
[INFO] Clojure grammar .................................... SUCCESS [  0.338 s]
[INFO] Cobol85 grammar .................................... SUCCESS [  2.186 s]
[INFO] CPP14 grammar ...................................... SUCCESS [  2.354 s]
[INFO] khubla.com creole grammar .......................... SUCCESS [  1.049 s]
[INFO] ANTLR CSV grammar .................................. SUCCESS [  0.266 s]
[INFO] khubla.com DateTime grammar ........................ SUCCESS [  0.358 s]
[INFO] DCM grammar ........................................ SUCCESS [  0.321 s]
[INFO] ANTLR dot grammar .................................. SUCCESS [  0.458 s]
[INFO] ECMAScript grammar ................................. SUCCESS [  1.161 s]
[INFO] Erlang grammar ..................................... SUCCESS [  1.200 s]
[INFO] khubla.com fasta grammar ........................... SUCCESS [  1.745 s]
[INFO] First Order Logic grammar .......................... SUCCESS [  0.429 s]
[INFO] fortran77 grammar .................................. SUCCESS [  0.938 s]
[INFO] fusion-tables grammar .............................. SUCCESS [  0.302 s]
[INFO] khubla.com gff3 grammar ............................ SUCCESS [  0.385 s]
[INFO] GraphQL grammar .................................... SUCCESS [  0.256 s]
[INFO] khubla.com html grammar ............................ SUCCESS [  0.194 s]
[INFO] ical grammar ....................................... SUCCESS [  3.286 s]
[INFO] IDL grammar ........................................ SUCCESS [  1.218 s]
[INFO] informix grammar ................................... SUCCESS [  2.640 s]
[INFO] IRI grammar ........................................ SUCCESS [  0.663 s]
[INFO] Java grammar ....................................... SUCCESS [  0.990 s]
[INFO] Java8 grammar ...................................... SUCCESS [  2.288 s]
[INFO] Javadoc grammar .................................... SUCCESS [  0.483 s]
[INFO] JPA grammar ........................................ SUCCESS [  0.829 s]
[INFO] ANTLR JSON grammar ................................. SUCCESS [  0.249 s]
[INFO] kuka grammar ....................................... SUCCESS [  0.685 s]
[INFO] less grammar ....................................... SUCCESS [  0.288 s]
[INFO] khubla.com logo grammar ............................ SUCCESS [  1.942 s]
[INFO] khubla.com lolcode grammar ......................... SUCCESS [  0.412 s]
[INFO] Lua grammar ........................................ SUCCESS [  0.561 s]
[INFO] MASM grammar ....................................... SUCCESS [  0.317 s]
[INFO] mdx grammar ........................................ SUCCESS [  0.326 s]
[INFO] memcached grammar .................................. SUCCESS [  0.514 s]
[INFO] Modelica grammar ................................... SUCCESS [  0.923 s]
[INFO] Modula2 PIM4 grammar ............................... SUCCESS [  0.769 s]
[INFO] MPS grammar ........................................ SUCCESS [  0.539 s]
[INFO] muMath grammar ..................................... SUCCESS [  0.357 s]
[INFO] khubla.com MUMPS grammar ........................... SUCCESS [  1.162 s]
[INFO] MySQL grammar ...................................... SUCCESS [  0.583 s]
[INFO] ANTLR Objective C grammar .......................... SUCCESS [  2.403 s]
[INFO] khubla.com Pascal grammar .......................... SUCCESS [  2.238 s]
[INFO] PCRE grammar ....................................... SUCCESS [  1.391 s]
[INFO] pddl logo grammar .................................. SUCCESS [  0.374 s]
[INFO] khubla.com logo grammar ............................ SUCCESS [  2.807 s]
[INFO] PeopleCode grammar ................................. SUCCESS [  2.812 s]
[INFO] Antlr pgn grammar .................................. FAILURE [  0.244 s]
[INFO] plsql grammar ...................................... SKIPPED
[INFO] khubla.com postalcode grammar ...................... SKIPPED
[INFO] khubla.com Propositional Calculus grammar .......... SKIPPED
[INFO] Python3 grammar .................................... SKIPPED
[INFO] R grammar .......................................... SKIPPED
[INFO] RCS ................................................ SKIPPED
[INFO] khubla.com RedCode grammar ......................... SKIPPED
[INFO] khubla.com RobotWar grammar ........................ SKIPPED
[INFO] Ruby-like language (Corundum) grammar .............. SKIPPED
[INFO] Scala grammar ...................................... SKIPPED
[INFO] scss grammar ....................................... SKIPPED
[INFO] sexpression grammar ................................ SKIPPED
[INFO] ADSP 2106x SHARC assembly language ................. SKIPPED
[INFO] Smalltalk grammar .................................. SKIPPED
[INFO] khubla.com SNOBOL grammar .......................... SKIPPED
[INFO] ANTLR4 Sparql grammar .............................. SKIPPED
[INFO] SQLite grammar ..................................... SKIPPED
[INFO] stacktrace grammar ................................. SKIPPED
[INFO] stringtemplate grammar ............................. SKIPPED
[INFO] SUOKIF grammar ..................................... SKIPPED
[INFO] ANTLR Swift grammar ................................ SKIPPED
[INFO] Swift FIN grammar .................................. SKIPPED
[INFO] khubla.com tiny grammar ............................ SKIPPED
[INFO] khubla.com tinyc grammar ........................... SKIPPED
[INFO] tnsnames grammar ................................... SKIPPED
[INFO] khubla.com TNT grammar ............................. SKIPPED
[INFO] tsql grammar ....................................... SKIPPED
[INFO] ANTLR turtle grammar ............................... SKIPPED
[INFO] UCB logo grammar ................................... SKIPPED
[INFO] VB6 grammar ........................................ SKIPPED
[INFO] VBA grammar ........................................ SKIPPED
[INFO] verilog grammar .................................... SKIPPED
[INFO] ANTLR4 vhdl grammar ................................ SKIPPED
[INFO] Wavefront grammar .................................. SKIPPED
[INFO] webidl grammar ..................................... SKIPPED
[INFO] ANTLR XML grammar .................................. SKIPPED
[INFO] XPath grammar ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:11 min
[INFO] Finished at: 2016-07-28T19:38:36-04:00
[INFO] Final Memory: 71M/934M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.antlr:antlr4test-maven-plugin:1.3-SNAPSHOT:test (default) on project pgn: Unable execute mojo: InvocationTargetException: ParseCancellationException: InputMismatchException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pgn
D:\grammars-v4-master>

**Comment by teverett** [comment] 2016-09-22 02:27
try it again after pulling trunk?

**Comment by teverett** [comment] 2017-04-12 14:08
I believe that this was caused by a OS X resource for ".DS_Store" having been committed to the tree. It would have worked properly on OS X but failed on Windows.  The resource fork was removed in this commit

https://github.com/antlr/grammars-v4/commit/e5c8dfbe355f544f2f1adb57840fee7fd20c0049

**Closed by teverett** 2017-04-12 14:08 UTC
